{
	"version": 1558881979,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/scene_1_page_1-sheet0.png",
		"images/scene_2_page_2-sheet0.png",
		"images/parchemin-sheet0.png",
		"images/parchemin-sheet1.png",
		"images/parchemin-sheet2.png",
		"images/buttonnext-sheet0.png",
		"images/animation_flip-sheet0.png",
		"images/animation_flip-sheet1.png",
		"images/animation_flip-sheet2.png",
		"images/animation_flip-sheet3.png",
		"images/dark_block_intermediary-sheet0.png",
		"images/scene_3_page_3___etc-sheet0.png",
		"images/parchment_example-sheet0.png",
		"images/tiledbackground.png",
		"images/flip_page_example-sheet0.png",
		"images/oldbook-sheet0.png",
		"images/butterfly-sheet0.png",
		"images/butterfly-sheet1.png",
		"images/butterfly-sheet2.png",
		"images/butterfly-sheet3.png",
		"images/butterfly-sheet4.png",
		"images/flower-sheet0.png",
		"images/mushroom-sheet0.png",
		"images/mushroom-sheet1.png",
		"images/mushroom-sheet2.png",
		"images/logohome-sheet0.png",
		"media/roll parchement.ogg",
		"media/unroll parchement.ogg",
		"media/turn page.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}